services:
  # Project URL: https://github.com/n8n-io/n8n
  # Docs URL: https://docs.n8n.io/
  n8n:
    image: docker.n8n.io/n8nio/n8n

    container_name: "n8n"
    restart: always    
    environment:
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - WEBHOOK_URL=${NGROK_URL}
    
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    
    deploy:
      resources:  
        limits:
          cpus: '1'
          memory: 2048M
  
  ngrok:
    image: ngrok/ngrok
    container_name: "ngrok"
    restart: unless-stopped
    command: http n8n:5678
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - n8n

volumes:
  n8n_data:
    driver: local
    
      
