# Scan branch with sonarqube on push
name: SonarQube Scan

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # If you have a sonar-project.properties, you can remove the args below.
          args: >
            -Dsonar.projectKey="${{ github.event.repository.name }}-${{ github.ref_name }}"
            -Dsonar.projectName="${{ github.event.repository.name }}-${{ github.ref_name }}"

          # Not supported for Community Edition
          # -Dsonar.branch.name=${{ github.ref_name }}

      # Optional: Wait for Quality Gate result (fails the job if not passed)
      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5

        
    